### ISSUE TITLE
missing lots of thumbnails...

### ISSUE THREAD

**Issue by ghost** [libretro-thumbnails/FBNeo_-_Arcade_Games#7]
using QT ui to download thumbnails from existing playlist (5256 current detected, using import method) and its  missing a lot of them

![screenshot_2018-12-18_10-49-06](https://user-images.githubusercontent.com/23315382/50129646-eb815000-02b4-11e9-88fe-45512a435834.png)

**Comment by RobLoach** [comment]
See the status over at:
https://raw.githubusercontent.com/RobLoach/libretro-thumbnails-check/master/out/FB%20Alpha%20-%20Arcade%20Games.txt
